//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanCafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODOANHTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOCAODOANHTHU()
        {
            this.CT_BAOCAODOANHTHU = new HashSet<CT_BAOCAODOANHTHU>();
        }
    
        public string MaBC { get; set; }
        public string TenBC { get; set; }
        public Nullable<System.DateTime> NgayBC { get; set; }
        public Nullable<decimal> TongDoanhThu { get; set; }
        public Nullable<decimal> LoiNhuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAOCAODOANHTHU> CT_BAOCAODOANHTHU { get; set; }
    }
}
