//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanCafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BAOCAODOANHTHU
    {
        public string MaCTBC { get; set; }
        public string MaBC { get; set; }
        public string MaLSP { get; set; }
        public Nullable<decimal> DoanhThu { get; set; }
    
        public virtual BAOCAODOANHTHU BAOCAODOANHTHU { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
