//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanCafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SANPHAM
    {
        public int MaCTSP { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaHH { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
