//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanCafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public string TS { get; set; }
        public Nullable<decimal> LuongTheoGio { get; set; }
        public Nullable<short> DiemTichLuyDatMon { get; set; }
        public Nullable<short> DiemToiThieuCoQua { get; set; }
    }
}
