//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_QuanCafe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THETICHDIEM
    {
        public int MaThe { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<short> DiemTichLuy { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
